import groovy.json.JsonSlurper

def slurper = new JsonSlurper()

def projectRootDir = System.getProperty("user.dir")

def json = slurper.parse(new File("${projectRootDir}/mozconfig.json"))

gradle.ext.mozconfig = json
gradle.ext.mozconfig.substs.MOZ_APP_VERSION = file("${projectRootDir}/version.txt").getText('utf-8').replaceAll("\n", "")
gradle.ext.mozconfig.substs.MOZ_ANDROID_FAT_AAR_ARCHITECTURES = true
gradle.ext.mozconfig.substs.MOZ_UPDATE_CHANNEL = 'release'
gradle.ext.mozconfig.substs.ALLOW_INSECURE_GRADLE_REPOSITORIES = true
gradle.ext.mozconfig.substs.ANDROID_BUILD_TOOLS_VERSION = "36.0.0" // build/moz.configure/android-sdk.configure#L140
gradle.ext.mozconfig.substs.NIMBUS_FML = "${projectRootDir}/dist/host/bin/nimbus-fml"
gradle.ext.mozconfig.substs.GRADLE_GLEAN_PARSER_VENV = "${projectRootDir}/venv"
gradle.ext.mozconfig.topsrcdir = System.getProperty("user.dir")
gradle.ext.mozconfig.topobjdir = System.getProperty("user.dir")

gradle.startParameter.offline = false

gradle.ext.configureMavenRepositories = { handler ->
    gradle.mozconfig.substs.GRADLE_MAVEN_REPOSITORIES.each { repository ->
        handler.maven {
            url = repository
            if (gradle.mozconfig.substs.ALLOW_INSECURE_GRADLE_REPOSITORIES) {
                allowInsecureProtocol = true
            }
        }
    }
}
