name: CI

on:
  push:
    branches:
      - iceraven

jobs:
  release-automation:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Install Android SDK with pieces Gradle skips
        run: ./automation/iceraven/install-sdk.sh

      - name: Inspect memory
        run: free -h

      - name: Create version name
        run: echo "VERSION_NAME=$(git describe --tags HEAD)" >> $GITHUB_ENV

      - name: Patch on the fly
        run: |
          ./automation/iceraven/patch_android_components.sh
          ./automation/iceraven/setup_venv.sh

      - name: Relpace strings
        run: |
          sed -i 's/Firefox/Iceraven/g' app/src/*/res/values*/*strings.xml
          sed -i '/about_content/s/Mozilla/@forkmaintainers/' app/src/*/res/values*/*strings.xml
          sed -i '/<string name="trackers_blocked_panel_categorical_num_trackers_blocked">/s/%s/%1$s/g; /<string name="trackers_blocked_panel_categorical_num_trackers_blocked">/s/%d/%2$d/g' app/src/*/res/values*/*strings.xml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build forkRelease variant of app
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=4g -Xms1g -Xmx7g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dev/stderr"
        run: |
          /usr/bin/time -v ./gradlew app:assembleForkRelease -PversionName=${{ env.VERSION_NAME }} --stacktrace --no-daemon

      - name: Debug
        run: |
          /usr/bin/ls -alh gradle/build/app/outputs/apk/forkRelease/

      - name: Create signed APKs
        uses: akliuxingyuan/sign-android-release@v2.0.1
        with:
          releaseDir: gradle/build/app/outputs/apk/forkRelease/
          signingKey: ${{ secrets.DEBUG_SIGNING_KEY }}
          keyAlias: ${{ secrets.DEBUG_ALIAS }}
          keyStorePassword: ${{ secrets.DEBUG_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}

      - name: Debug
        run: |
          /usr/bin/ls -alh gradle/build/app/outputs/apk/forkRelease/

      - name: Upload arm64 apk
        uses: actions/upload-artifact@v7
        with:
          path: gradle/build/app/outputs/apk/forkRelease/app-arm64-v8a-forkRelease.apk
          name: ${{ env.VERSION_NAME }}-arm64-v8a.apk

      - name: Upload armeabi apk
        uses: actions/upload-artifact@v7
        with:
          path: gradle/build/app/outputs/apk/forkRelease/app-armeabi-v7a-forkRelease.apk
          name: ${{ env.VERSION_NAME }}-armeabi-v7a.apk

      - name: Upload x86_64 apk
        uses: actions/upload-artifact@v7
        with:
          path: gradle/build/app/outputs/apk/forkRelease/app-x86_64-forkRelease.apk
          name: ${{ env.VERSION_NAME }}-x86_64.apk
